// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BookedTicket struct {
	ID        uuid.UUID
	ConcertID uuid.UUID
	UserID    uuid.UUID
}

type ConcertTicket struct {
	ID                   uuid.UUID
	TotalTickets         sql.NullInt32
	ConcertName          sql.NullString
	TicketAvailableCount sql.NullInt32
}

type ConcertTickets1 struct {
	ID                   uuid.UUID
	TotalTickets         sql.NullInt32
	ConcertName          sql.NullString
	TicketAvailableCount sql.NullInt32
}

type ConcertTickets2 struct {
	ID                   uuid.UUID
	TotalTickets         sql.NullInt32
	ConcertName          sql.NullString
	TicketAvailableCount sql.NullInt32
}

type ConcertTickets3 struct {
	ID                   uuid.UUID
	TotalTickets         sql.NullInt32
	ConcertName          sql.NullString
	TicketAvailableCount sql.NullInt32
}

type ConcertTickets4 struct {
	ID                   uuid.UUID
	TotalTickets         sql.NullInt32
	ConcertName          sql.NullString
	TicketAvailableCount sql.NullInt32
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Name      string
}
